# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e56827d5de018f45ca4e490f0da00064fab07a500dc22074e7a73985549c48f4b7440f63f4f02547cf2c1325b4bf7db4099596a457ab1dad55ecc32f9a802d

test:
  secret_key_base: 4c5963e22e02c1775a417d94c3370561d075c9bf8497544645b55f502da18742e8fb469b2a786168ea5282d313bd596088d62ae58b0725a21c51cc3bdc3887fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
